### ISSUE TITLE
The Value 'GBP' is invalid for the Parameter 'currencyCode'

### ISSUE THREAD

**Issue by daroPL** [amzn/amazon-payments-magento-plugin#135]
While making an order in the GBP currency I see the following error, but it works with USD.
```
exception 'OffAmazonPaymentsService_Exception' with message 'The Value 'GBP' is invalid for the Parameter 'currencyCode'' in /srv/www/site.co.uk/lib/OffAmazonPaymentsService/Client.php:914
Stack trace:
#0 /srv/www/site.co.uk/lib/OffAmazonPaymentsService/Client.php(862): OffAmazonPaymentsService_Client->_reportAnyErrors('<ErrorResponse ...', 400, Object(OffAmazonPaymentsService_Model_ResponseHeaderMetadata))
#1 /srv/www/site.co.uk/lib/OffAmazonPaymentsService/Client.php(533): OffAmazonPaymentsService_Client->_invoke(Array)
#2 /srv/www/site.co.uk/app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->setOrderReferenceDetails(Object(OffAmazonPaymentsService_Model_SetOrderReferenceDetailsRequest))
#3 /srv/www/site.co.uk/app/code/community/Amazon/Payments/Model/Api.php(302): Amazon_Payments_Model_Api->request('setOrderReferen...', Array)
#4 /srv/www/site.co.uk/app/code/community/Amazon/Payments/Model/PaymentMethod.php(237): Amazon_Payments_Model_Api->setOrderReferenceDetails('P01-6052816-987...', 10.24, 'GBP', '300024462', 'site...')
#5 /srv/www/site.co.uk/app/code/community/Amazon/Payments/Model/PaymentMethod.php(84): Amazon_Payments_Model_PaymentMethod->order(Object(Mage_Sales_Model_Order_Payment), 10.24)
#6 /srv/www/site.co.uk/app/code/core/Mage/Sales/Model/Order/Payment.php(303): Amazon_Payments_Model_PaymentMethod->initialize('authorize_captu...', Object(Varien_Object))
#7 /srv/www/site.co.uk/app/code/core/Mage/Sales/Model/Order.php(877): Mage_Sales_Model_Order_Payment->place()
#8 /srv/www/site.co.uk/app/code/core/Mage/Sales/Model/Order.php(1095): Mage_Sales_Model_Order->_placePayment()
#9 [internal function]: Mage_Sales_Model_Order->place()
#10 /srv/www/site.co.uk/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#11 /srv/www/site.co.uk/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#12 /srv/www/site.co.uk/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#13 /srv/www/site.co.uk/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#14 /srv/www/site.co.uk/app/code/community/Amazon/Payments/Model/Type/Checkout.php(136): Mage_Sales_Model_Service_Quote->submitAll()
#15 /srv/www/site.co.uk/app/code/community/Amazon/Payments/controllers/CheckoutController.php(235): Amazon_Payments_Model_Type_Checkout->saveOrder()
#16 /srv/www/site.co.uk/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Amazon_Payments_CheckoutController->saveOrderAction()
#17 /srv/www/site.co.uk/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#18 /srv/www/site.co.uk/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /srv/www/site.co.uk/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#20 /srv/www/site.co.uk/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#21 /srv/www/site.co.uk/index.php(93): Mage::run('site...', 'store')
#22 {main}
```

**Comment by rjamison** [comment]
This extension currently only supports US Amazon Payments accounts, which can only transact in USD. UK/DE Sellers can use this extension:  

http://www.magentocommerce.com/magento-connect/login-and-pay-with-amazon-advanced-payment-apis-for-europe.html
