### ISSUE TITLE
Error We're sorry, but there's a problem processing your payment from this website

### ISSUE THREAD

**Issue by hzubyrss** [amzn/amazon-payments-magento-plugin#312]
On my store many customer having problem with Amazon payment it happen some time and most of the time works fine any help please ? see the screenshot of error 
[https://snag.gy/qxwtj0.jpg](url)

Here is error report 

```
a:5:{i:0;s:1978:"exception 'OffAmazonPaymentsService_Exception' with message 'Unable to post request, underlying exception of Couldn't resolve host 'mws.amazonservices.com''
 in /home/storepro/public_html/lib/OffAmazonPaymentsService/Client.php:1000
Stack trace:
#0 /home/storepro/public_html/lib/OffAmazonPaymentsService/Client.php(844): OffAmazonPaymentsService_Client->_httpPost(Array)
#1 /home/storepro/public_html/lib/OffAmazonPaymentsService/Client.php(487): OffAmazonPaymentsService_Client->_invoke(Array)
#2 /home/storepro/public_html/app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->getOrderReferenceDetails(Object(OffAmazonPaymentsService_Model_GetOrderReferenceDetailsRequest))
#3 /home/storepro/public_html/app/code/community/Amazon/Payments/Model/Api.php(241): Amazon_Payments_Model_Api->request('getOrderReferen...', Array)
#4 /home/storepro/public_html/app/code/community/Amazon/Payments/Controller/Checkout.php(258): Amazon_Payments_Model_Api->getOrderReferenceDetails('P01-4215216-768...', 'Atza|IwEBIIxCl8...')
#5 /home/storepro/public_html/app/code/community/Amazon/Payments/controllers/CheckoutController.php(129): Amazon_Payments_Controller_Checkout->_saveShipping()
#6 /home/storepro/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->addressSelectAction()
#7 /home/storepro/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('addressSelect')
#8 /home/storepro/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /home/storepro/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#10 /home/storepro/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /home/storepro/public_html/index.php(83): Mage::run('', 'store')
#12 {main}";i:1;s:1417:"#0 /home/storepro/public_html/app/code/community/Amazon/Payments/Model/Api.php(102): Mage::throwException(Object(OffAmazonPaymentsService_Exception))
#1 /home/storepro/public_html/app/code/community/Amazon/Payments/Model/Api.php(241): Amazon_Payments_Model_Api->request('getOrderReferen...', Array)
#2 /home/storepro/public_html/app/code/community/Amazon/Payments/Controller/Checkout.php(258): Amazon_Payments_Model_Api->getOrderReferenceDetails('P01-4215216-768...', 'Atza|IwEBIIxCl8...')
#3 /home/storepro/public_html/app/code/community/Amazon/Payments/controllers/CheckoutController.php(129): Amazon_Payments_Controller_Checkout->_saveShipping()
#4 /home/storepro/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->addressSelectAction()
#5 /home/storepro/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('addressSelect')
#6 /home/storepro/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /home/storepro/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#8 /home/storepro/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /home/storepro/public_html/index.php(83): Mage::run('', 'store')
#10 {main}";s:3:"url";s:40:"/checkout/amazon_payments/addressSelect/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```

**Comment by islandskater43** [comment]
Hello @hzubyrss - do you have any functionality that blocks outgoing requests, or have you done any IP whitelisting for API calls to mws.amazonservices.com?

**Comment by islandskater43** [comment]
Closing. If you are still experiencing the issue, feel free to reopen.
