### ISSUE TITLE
Exception: is not in draft state and cannot be modified

### ISSUE THREAD

**Issue by sagar-bhatt** [amzn/amazon-payments-magento-plugin#345]
I am using this module for Magento EE 1.4 
I have an issue with one order which is authorized and captured on Amazon Pay portal but doesn't exist in Magento. The reason for that is also pretty much clear since I can see an exception in Magento for that order which states:
`"exception 'OffAmazonPaymentsService_Exception' with message 'OrderReference P01-XXXXXXX-YYYYYYY is not in draft state and cannot be modified with the request submitted by you.' in /var/app/current/public/lib/OffAmazonPaymentsService/Client.php:914"`

with the error status code of 405.
![t3-amazon-pay-exception](https://user-images.githubusercontent.com/12719708/33729289-f9e54760-db31-11e7-8049-746b842c2717.PNG)

I could see multiple reasons for getting 405 as specified in here:
https://pay.amazon.com/us/developer/documentation/apireference/201753060

But I am not sure how and why did that happen?
I didn't have Debug mode turned on at that time, so don't have more information to share.

Any ideas?
Thank you.

**Comment by prayagr** [comment]
Hello @sagar-bhatt , thanks for reaching out.  Assuming you meant EE 1.14, can you share more details around how to reproduce this issue? Are you able to reproduce it consistently?

The error seems to be due to calling the setOrderReferenceDetails API. If an order is already confirmed, you won't be able to modify it by calling the setOrderReferenceDetails API. A potential reason could be that the browser back button was clicked after placing the order. In this case, we may see this error as the order has already been confirmed and you won't be able to make changes in either the wallet or the address widget, resulting in this error.

**Comment by jmonrove** [comment]
We Experienced the same error on 1.14.0.1, it resulted on the order being charged on Amazon Pay and not saved into the Magento DB, I am not aware of a way to replicate this error.

this is the trace we got:

`
exception 'OffAmazonPaymentsService_Exception' with message 'OrderReference XXXXXXX is not in draft state and cannot be modified with the request submitted by you.' in lib/OffAmazonPaymentsService/Client.php:920

Stack trace:

#0 lib/OffAmazonPaymentsService/Client.php(868): OffAmazonPaymentsService_Client->_reportAnyErrors('<ErrorResponse ...', 405, Object(OffAmazonPaymentsService_Model_ResponseHeaderMetadata))

#1 lib/OffAmazonPaymentsService/Client.php(539): OffAmazonPaymentsService_Client->_invoke(Array)

#2 app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->setOrderReferenceDetails(Object(OffAmazonPaymentsService_Model_SetOrderReferenceDetailsRequest))

#3 app/code/community/Amazon/Payments/Model/Api.php(306): Amazon_Payments_Model_Api->request('setOrderReferen...', Array)

#4 app/code/community/Amazon/Payments/Model/PaymentMethod.php(379): Amazon_Payments_Model_Api->setOrderReferenceDetails('XXXXXXX', YYYYY, 'USD', 'ZZZZZ', 'AAAAAAAAA.')

#5 app/code/community/Amazon/Payments/Model/PaymentMethod.php(121): Amazon_Payments_Model_PaymentMethod->order(Object(Mage_Sales_Model_Order_Payment), 166.04)

#6 app/code/core/Mage/Sales/Model/Order/Payment.php(334): Amazon_Payments_Model_PaymentMethod->initialize('authorize_captu...', Object(Varien_Object))

#7 app/code/local/Mage/Sales/Model/Order.php(886): Mage_Sales_Model_Order_Payment->place()

#8 app/code/local/Mage/Sales/Model/Order.php(1115): Mage_Sales_Model_Order->_placePayment()

#9 [internal function]: Mage_Sales_Model_Order->place()

#10 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)

#11 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()

#12 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()

#13 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()

#14 app/code/community/Amazon/Payments/Model/Type/Checkout.php(210): Mage_Sales_Model_Service_Quote->submitAll()

#15 app/code/community/Amazon/Payments/controllers/CheckoutController.php(321): Amazon_Payments_Model_Type_Checkout->saveOrder()

#16 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->saveOrderAction()

#17 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')

#18 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))

#19 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()

#20 app/Mage.php(684): Mage_Core_Model_App->run(Array)

#21 index.php(101): Mage::run('', 'store')

#22 {main}
`

**Comment by tarishah** [comment]
@jmonrove Thanks for reaching out. We are looking into this. 

I will reach back out here, once we have an update.
