### ISSUE TITLE
md one step checkout not working

### ISSUE THREAD

**Issue by brajesh872** [amzn/amazon-payments-magento-plugin#371]
in md one step checkout, after login in checkout page, error show is
	Fatal error: Uncaught Error: Call to a member function getId() on boolean in /home/marathikaraoke/public_html/magc/app/code/local/MD/Onestepcheckout/Block/Onestepcheckout.php:292 Stack trace: #0 /home/marathikaraoke/public_html/magc/app/code/local/MD/Onestepcheckout/Block/Onestepcheckout.php(345): MD_Onestepcheckout_Block_Onestepcheckout->getAddress() #1 /home/marathikaraoke/public_html/magc/app/design/frontend/base/default/template/onestepcheckout/onestepcheckout/billing.phtml(6): MD_Onestepcheckout_Block_Onestepcheckout->getAddressesHtmlSelect('billing') #2 /home/marathikaraoke/public_html/magc/app/code/core/Mage/Core/Block/Template.php(241): include('/home/marathika...') #3 /home/marathikaraoke/public_html/magc/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...') #4 /home/marathikaraoke/public_html/magc/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView() #5 /home/marathikaraoke/public_html/magc/app/code/core/Mage/Core/Block/Abstra in /home/marathikaraoke/public_html/magc/app/code/local/MD/Onestepcheckout/Block/Onestepcheckout.php on line 292

**Comment by tarishah** [comment]
@brajesh872 Thanks for reaching out. Can you tell us which OSC are you using?

Is it https://github.com/flintdigital/mage-mod-osc-magedrive ?

Additionally, can you reach out to us at payments-cp-devel@amazon.com with screenshots of the Amazon Pay settings, specifically the 'Checkout Page Type' value (refer https://github.com/amzn/amazon-payments-magento-plugin/wiki/Configuration#checkout-configuration). Try selecting 'Standalone Checkout' and then test Amazon Pay. 

Look forward to hear from you.

Thanks!
