### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function OffAmazonPaymentsService_Model_ConfirmOrderReferenceRequest::getSuccessUrl()

### ISSUE THREAD

**Issue by jasonkcarter** [amzn/amazon-payments-magento-plugin#381]
Release version 1.7.0
Steps to reproduce:
- Install and configure extension on Magento Open Source 1.9.4.2
- Add an item to the shopping cart
- Go to the shopping cart and click the Amazon Pay button
- During the final step of one step checkout, click the Place Order button
- An HTTP 500 error is thrown on the server

Error Logs / Stack Traces:
```
<18-Jul-2019 20:39:11 UTC> PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function OffAmazonPaymentsService_Model_ConfirmOrderReferenceRequest::getSuccessUrl(), 0 passed in lib/OffAmazonPaymentsService/Client.php on line 1392 and exactly 1 expected in lib/OffAmazonPaymentsService/Model/ConfirmOrderReferenceRequest.php:82
Stack trace:
#0 lib/OffAmazonPaymentsService/Client.php(1392): OffAmazonPaymentsService_Model_ConfirmOrderReferenceRequest->getSuccessUrl()
#1 lib/OffAmazonPaymentsService/Client.php(470): OffAmazonPaymentsService_Client->_convertConfirmOrderReference(Object(OffAmazonPaymentsService_Model_ConfirmOrderReferenceRequest))
#2 app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->confirmOrderReference(Object(OffAmazonPaymentsService_Model_ConfirmOrderRe in lib/OffAmazonPaymentsService/Model/ConfirmOrderReferenceRequest.php on line 82

[18-Jul-2019 20:54:57 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function OffAmazonPaymentsService_Model_ConfirmOrderReferenceRequest::getFailureUrl(), 0 passed in lib/OffAmazonPaymentsService/Client.php on line 1395 and exactly 1 expected in lib/OffAmazonPaymentsService/Model/ConfirmOrderReferenceRequest.php:115
Stack trace:
#0 lib/OffAmazonPaymentsService/Client.php(1395): OffAmazonPaymentsService_Model_ConfirmOrderReferenceRequest->getFailureUrl()
#1 lib/OffAmazonPaymentsService/Client.php(470): OffAmazonPaymentsService_Client->_convertConfirmOrderReference(Object(OffAmazonPaymentsService_Model_ConfirmOrderReferenceRequest))
#2 app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->confirmOrderReference(Object(OffAmazonPaymentsService_Model_ConfirmOrderR in lib/OffAmazonPaymentsService/Model/ConfirmOrderReferenceRequest.php on line 115
```

**Comment by tarishah** [comment]
@jasonkcarter Thanks for reaching out to us.

We are looking in to this and provide an update soon.
Tarini

**Comment by SpottedPaint** [comment]
I had the same error in version 1.6.0, applying the changes above worked for me. Hope that helps. I'm using the Magento Core OnePage Checkout

**Comment by tarishah** [comment]
@SpottedPaint Thanks for confirming!

closing this issue.
